#version 450

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(set = 0, binding = 0, std430) readonly buffer DummyA { uint value; } dummy_a;
layout(set = 0, binding = 1, std430) coherent volatile buffer Control { uint values[]; } control;
layout(set = 0, binding = 2, std430) readonly buffer DummyB { uint value; } dummy_b;
layout(set = 0, binding = 3, std430) readonly buffer DummyC { uint value; } dummy_c;
layout(push_constant) uniform Params { uvec4 unused; } params;

const uint REQUEST_STATE = 186u;

void main() {
    memoryBarrierBuffer();
    atomicExchange(control.values[REQUEST_STATE], 4u);
}
